import esbuild from 'esbuild';
import process from 'process';
import {builtinModules} from 'node:module';
import {copy} from 'esbuild-plugin-copy';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtinModules,
    ],
    plugins: [
        copy({
            assets: [{
                from: "./manifest.json",
                to: "./test-vault/.obsidian/plugins/simple-time-tracker/manifest.json"
            }, {
                from: "./main.js",
                to: "./test-vault/.obsidian/plugins/simple-time-tracker/main.js"
            }, {
                from: "./styles.css",
                to: "./test-vault/.obsidian/plugins/simple-time-tracker/styles.css"
            }]
        }),
    ],
    format: 'cjs',
    target: 'es2021',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
    minify: prod,
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
